local Type = require("Type")
local D = require("Definition")

return D.Definitions
{
    D.Enum("CheatCommandEnum", Type.U8,
    {
        D.Field("None"),
        D.Field("Damage"),
        D.Field("Heal"),
        D.Field("Kill"),
        D.Field("Resurrect"),
        D.Field("UnitMorph"),
        D.Field("UnitDemorph"),
        D.Field("Teleport"),
        D.Field("CharacterAdd"),
        D.Field("CharacterRemove"),
        D.Field("UnitSetRace"),
        D.Field("UnitSetGender"),
        D.Field("UnitSetClass"),
        D.Field("UnitSetLevel"),
        D.Field("ItemSetTemplate"),
        D.Field("ItemSetStatTemplate"),
        D.Field("ItemSetArmorTemplate"),
        D.Field("ItemSetWeaponTemplate"),
        D.Field("ItemSetShieldTemplate"),
        D.Field("ItemAdd"),
        D.Field("ItemRemove"),
        D.Field("CreatureAdd"),
        D.Field("CreatureRemove"),
        D.Field("CreatureInfo"),
        D.Field("GotoAdd", 26),
        D.Field("GotoAddHere"),
        D.Field("GotoRemove"),
        D.Field("GotoMap"),
        D.Field("GotoLocation"),
        D.Field("GotoXYZ"),
        D.Field("TriggerAdd"),
        D.Field("TriggerRemove"),
        D.Field("CreatureAddScript", 37),
        D.Field("CreatureRemoveScript"),
        D.Field("CreatureMove"),
        D.Field("CreatureFollow"),
        D.Field("CreatureWander"),
        D.Field("CreatureStop"),
        D.Field("FactionReaction"),
        D.Field("FactionReputationInfo"),
        D.Field("FactionReputationSet"),
        D.Field("FactionReputationModify"),
        D.Field("FactionReputationRemove"),
        D.Field("FactionReputationSetFlags"),
        D.Field("FactionReputationLock"),
        D.Field("UnitSetFaction"),
        D.Field("DatabaseEditor"),
        D.Field("DevelopmentAction", 57)
    })
}
