local Type = require("Type")
local D = require("Definition")

return D.Definitions
{
    D.Enum("CheatCommandEnum", Type.U8,
    {
        D.Field("None"),
        D.Field("Damage"),
        D.Field("Heal"),
        D.Field("Kill"),
        D.Field("Resurrect"),
        D.Field("UnitMorph"),
        D.Field("UnitDemorph"),
        D.Field("Teleport"),
        D.Field("CharacterAdd"),
        D.Field("CharacterRemove"),
        D.Field("UnitSetRace"),
        D.Field("UnitSetGender"),
        D.Field("UnitSetClass"),
        D.Field("UnitSetLevel"),
        D.Field("ItemSetTemplate"),
        D.Field("ItemSetStatTemplate"),
        D.Field("ItemSetArmorTemplate"),
        D.Field("ItemSetWeaponTemplate"),
        D.Field("ItemSetShieldTemplate"),
        D.Field("ItemAdd"),
        D.Field("ItemRemove"),
        D.Field("CreatureAdd"),
        D.Field("CreatureRemove"),
        D.Field("CreatureInfo"),
        D.Field("MapAdd"),
        D.Field("GotoAdd"),
        D.Field("GotoAddHere"),
        D.Field("GotoRemove"),
        D.Field("GotoMap"),
        D.Field("GotoLocation"),
        D.Field("GotoXYZ"),
        D.Field("TriggerAdd"),
        D.Field("TriggerRemove"),
        D.Field("SpellSet"),
        D.Field("SpellEffectSet"),
        D.Field("SpellProcDataSet"),
        D.Field("SpellProcLinkSet"),
        D.Field("CreatureAddScript"),
        D.Field("CreatureRemoveScript"),
        D.Field("CreatureMove"),
        D.Field("CreatureFollow"),
        D.Field("CreatureWander"),
        D.Field("CreatureStop")
    })
}
