local M = {}

local foreignKeyActions =
{
    noAction = "NO ACTION",
    restrict = "RESTRICT",
    cascade = "CASCADE",
    setNull = "SET NULL",
    setDefault = "SET DEFAULT"
}

local checkOperators =
{
    equal = "=",
    notEqual = "<>",
    greaterThan = ">",
    greaterEqual = ">=",
    lessThan = "<",
    lessEqual = "<="
}

local function QuoteIdentifier(identifier)
    return "\"" .. identifier:gsub("\"", "\"\"") .. "\""
end

local function QualifiedName(tableModel)
    return QuoteIdentifier(tableModel.schema) .. "." .. QuoteIdentifier(tableModel.tableName)
end

local function SqlLiteral(field, value)
    local category = field.postgresType.category
    if category == "string" then return "'" .. value:gsub("'", "''") .. "'" end
    if category == "boolean" then return value and "TRUE" or "FALSE" end
    if category == "integer" or category == "float" then return tostring(value) end
    local name = field.postgresType.name
    if name == "text" or name:match("^varchar%(") then return "'" .. value:gsub("'", "''") .. "'" end
    if name == "boolean" then return value and "TRUE" or "FALSE" end
    if name == "smallint" or name == "integer" or name == "bigint" or name == "real" or
        name == "double precision" or name:match("^numeric") or name:match("^decimal") then
        return tostring(value)
    end
    error("No SQL literal conversion for PostgreSQL type '" .. tostring(field.postgresType.name) .. "'", 0)
end

local function ColumnList(fields, includeDirection)
    local columns = {}
    for _, reference in ipairs(fields) do
        local value = QuoteIdentifier(reference.columnName or reference.field.columnName)
        if includeDirection then value = value .. " " .. reference.direction:upper() end
        columns[#columns + 1] = value
    end
    return table.concat(columns, ", ")
end

local function ColumnDefinition(field)
    local parts = { QuoteIdentifier(field.columnName), field.postgresType.sql }
    if field.identity == "always" then
        parts[#parts + 1] = "GENERATED ALWAYS AS IDENTITY"
    elseif field.identity == "byDefault" then
        parts[#parts + 1] = "GENERATED BY DEFAULT AS IDENTITY"
    elseif field.hasDefault then
        parts[#parts + 1] = "DEFAULT " .. SqlLiteral(field, field.defaultValue)
    end
    parts[#parts + 1] = field.nullable and "NULL" or "NOT NULL"
    return table.concat(parts, " ")
end

local function CheckExpression(constraint)
    local field = constraint.fields[1].field
    local column = QuoteIdentifier(field.columnName)
    if constraint.operator == "isTrue" then return column .. " IS TRUE" end
    if constraint.operator == "isFalse" then return column .. " IS FALSE" end
    if constraint.operator == "in" then
        local values = {}
        for _, value in ipairs(constraint.value) do values[#values + 1] = SqlLiteral(field, value) end
        return column .. " IN (" .. table.concat(values, ", ") .. ")"
    end
    return column .. " " .. checkOperators[constraint.operator] .. " " .. SqlLiteral(field, constraint.value)
end

local function ConstraintDefinition(constraint)
    local prefix = "CONSTRAINT " .. QuoteIdentifier(constraint.name) .. " "
    if constraint.kind == "unique" then
        return prefix .. "UNIQUE (" .. ColumnList(constraint.fields, false) .. ")"
    end
    if constraint.kind == "foreignKey" then
        return prefix .. "FOREIGN KEY (" .. ColumnList(constraint.fields, false) .. ") REFERENCES " ..
            QualifiedName(constraint.target) .. " (" .. ColumnList(constraint.targetFields, false) .. ")" ..
            " ON UPDATE " .. foreignKeyActions[constraint.onUpdate] ..
            " ON DELETE " .. foreignKeyActions[constraint.onDelete]
    end
    if constraint.kind == "check" then return prefix .. "CHECK (" .. CheckExpression(constraint) .. ")" end
    if constraint.kind == "rawCheck" then return prefix .. "CHECK (" .. constraint.rawSql .. ")" end
    error("Unsupported PostgreSQL constraint kind '" .. tostring(constraint.kind) .. "'", 0)
end

local function TableSql(tableModel)
    local entries = {}
    for _, field in ipairs(tableModel.fields) do entries[#entries + 1] = ColumnDefinition(field) end
    if tableModel.primaryKey ~= nil then
        entries[#entries + 1] = "CONSTRAINT " .. QuoteIdentifier(tableModel.primaryKey.name) ..
            " PRIMARY KEY (" .. ColumnList(tableModel.primaryKey.fields, false) .. ")"
    end
    for _, constraint in ipairs(tableModel.constraints) do entries[#entries + 1] = ConstraintDefinition(constraint) end

    local lines = { "CREATE TABLE " .. QualifiedName(tableModel), "(" }
    for index, entry in ipairs(entries) do
        lines[#lines + 1] = "    " .. entry .. (index < #entries and "," or "")
    end
    lines[#lines + 1] = ");"
    return table.concat(lines, "\n")
end

local function IndexSql(tableModel, index)
    return "CREATE " .. (index.unique and "UNIQUE " or "") .. "INDEX " .. QuoteIdentifier(index.name) ..
        " ON " .. QualifiedName(tableModel) .. " (" .. ColumnList(index.fields, true) .. ");"
end

function M.GenerateBundle(bundle)
    local sections =
    {
        "-- Generated by MetaGen. Do not edit.",
        "-- Logical database bundle: " .. bundle.name,
        "",
        "BEGIN;"
    }

    for _, schema in ipairs(bundle.schemas) do
        sections[#sections + 1] = "CREATE SCHEMA IF NOT EXISTS " .. QuoteIdentifier(schema.name) .. ";"
    end

    for _, tableModel in ipairs(bundle.tables) do
        sections[#sections + 1] = ""
        sections[#sections + 1] = TableSql(tableModel)
    end

    for _, tableModel in ipairs(bundle.tables) do
        for _, index in ipairs(tableModel.indexes) do
            sections[#sections + 1] = ""
            sections[#sections + 1] = IndexSql(tableModel, index)
        end
    end

    sections[#sections + 1] = ""
    sections[#sections + 1] = "COMMIT;"
    sections[#sections + 1] = ""
    return table.concat(sections, "\n")
end

M.QuoteIdentifier = QuoteIdentifier
M.QualifiedName = QualifiedName
M.ColumnDefinition = ColumnDefinition
M.TableSql = TableSql
M.IndexSql = IndexSql

return M
