include_guard(GLOBAL)

# Setup Cached Options
set(LUAU_BUILD_CLI OFF CACHE BOOL "" FORCE)
set(LUAU_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS_HO OFF CACHE BOOL "" FORCE)
set(TYPE_SAFE_BUILD_TEST_EXAMPLE OFF CACHE BOOL "" FORCE)

# Setup Non-Cached Options
set(ROOT_FOLDER ${PROJECT_NAME})
set(ROOT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})

if(NOT DEFINED NOVUSCORE_SETUP)
    set(CMAKE_CONFIGURATION_TYPES Debug Release RelWithDebInfo CACHE STRING "" FORCE)
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_DISABLE_SOURCE_CHANGES ON)
    set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin/Libs)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Bin)

    set(NOVUSCORE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
    set(NOVUSCORE_BUILD_DIR ${CMAKE_BINARY_DIR}/bin)
endif()