name: PR Windows Build

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  call-windows-build:
    if: ${{ github.event.label.name == 'build-win' }}
    uses: novusengine/Workflows/.github/workflows/win-build.yml@master
    with:
      project: Engine