name: PR Linux Build

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  call-linux-build:
    if: ${{ github.event.label.name == 'build-linux' }}
    name: Linux Build
    uses: ./.github/workflows/linux-build.yml
