name: PR Linux Build

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  call-linux-build:
    if: ${{ github.event.label.name == 'build-linux' }}
    uses: novusengine/Workflows/.github/workflows/linux-build.yml@master
    with:
      project: Engine