name: PR build-win label

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  call-windows-build:
    if: ${{ github.event.label.name == 'build-win' }}
    name: Windows Build
    uses: ./.github/workflows/win-build.yml
